public class oopsbasic {
    public static void main(String[] args) {
      /*
      
      1> ABSTRACTION- HIDING UNNESARY CODE( WHAT IT WORKS RATHER THAN HOW IT WORKS ) (PHONE - DONT KNOW HOW IT WORKS BUT KNOW ITS FUNCTIONALITIES)
      2> ENCAPSULATION - KEEPING SENSITIVE DATA TOGETHER LIKE IN A CAPSULE (LAPTOP CONTAINING EVERYTHING WIFI, SPEAKER, CAMARA ETC)
      3> INHERITANCE - USING SAME CODE FOR CREATING NEW THINGS (E RICKSAW FROM RICKSAW, SMART PHN FROM PHN)
      4> POLYMORFISM - USING SAME CODE FOR MULTIPLE PURPOSE ( PHN AS CAMERA, CALCULATOR, SPEAKER ETC)
    
      */  
    }

}
